config/routes.rb
Rails.application.routes.draw do
  devise_for :users
   #root "pages#home"
     root "videos#index"
    get "videos", to: "videos#index"
    get 'pages/private_page'
 

  resources :videos, :users , :comments
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end
  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :video
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/video.rb
class Video < ApplicationRecord
    has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def new
        @video = Video.find(params[:video_id])
        @comment = Comment.new
      end

def create
    # video = Video.find(params[:comment][:video_id])
    # Comment.create(params.require(:comment).permit(:content)
    # redirect_to videos_path
    comment = Comment.create(params.require(:comment).permit(:content, :video_id))
    comment.user_id = current_user.id
    comment.save
    redirect_to request.referer  
end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: :private_page
  def home
    @videos = Video.all
  end

  def private_page
    @email = current_user.email
end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
    def index
        @videos = Video.all  

    end
    def show
        @video = Video.find(params[:id])
      end
    
    def new
        if current_user.admin
            @video = Video.new
        else
             redirect_to videos_path, :notice => "You are not admin"
        end
    end
    
    def create
            Video.create(params.require(:video).permit(:title, :des, :url, :video_url))
            redirect_to videos_path     
    end
    
    def edit
        if current_user.admin
        @video = Video.find(params[:id])
    else
        redirect_to videos_path, :notice => "You are not admin"
    end
    end

    def update
        if current_user.admin
        video = Video.find(params[:id])
        video.update(params.require(:video).permit(:title, :des, :url, :video_url)) 
        redirect_to video
    else
        redirect_to videos_path, :notice => "You are not admin"
    end
        
    end
    
    def destroy
        if current_user.admin
        Video.find(params[:id]).destroy
        redirect_to videos_path
    else
        redirect_to videos_path, :notice => "You are not admin"
    end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/comments/_form.html.erb
<%= form_for @comment do |f| %>
  <%= f.hidden_field :video_id, :value => @video.id %>
  <div class="input-field col s6">
  	<%= f.label :content, 'Comment' %>
  <div>	<%= f.text_area :content %>
  </div>
<%# <%if @video%>
<%# <%= form.hidden_field :video_id, :value => @video.id%> 
<%# <%end%>  <%= f.submit "Submit", :class => "btn waves-effect waves-light" %> 
<% end %>

</div>

app/views/comments/new.html.erb
<h2>New Comment for <%= @video.title %></h1>

<%= render 'comments/form' %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
<a class="navbar-brand" href="http://localhost:3000"><img src="/assets/yogi.png", size: "16x10", alt: "yogo logo" />
</a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">
     
      <li class = "nav-item">
      <%= link_to('New Video', new_video_path, class: 'nav-item nav-link active') %>
     <li>
      
        <li class="nav-item">
      </li>
    </ul>
      <%if user_signed_in? %>
  <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:"nav-item"%>
  <%else %>
  <%=  link_to "Log In", new_user_session_path, class:"nav-item"%>
   <%=  link_to "Sign Up", new_user_registration_path, class:"nav-item"%>
  
  <%end %>
    <form class="form-inline mt-2 mt-md-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YogaComunityApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

    <p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
  <%=render 'layouts/nav'%>
      <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/private_page.html.erb
<p>Welcome <%= @email%></p>

app/views/videos/_form.html.erb
<%= form_for @video do |f| %>
  <div class="input-field col s6">
  	<%= f.label :title, 'Video Title : '%>
  	<%= f.text_field :title%>
  </div>
  <div class="input-field col s6">
  	<%= f.label :des, 'Description:' %>
  	<%= f.text_field :des %>
  </div>
  <div class="input-field col s6">
  	<%= f.label :url, 'Poster URL:' %>
  	<%= f.text_field :url %>
  </div>
    <div class="input-field col s6">
  	<%= f.label :video_url, 'Video URL :  ' %>
  	<%= f.text_field :video_url %>
  </div>
 
  <%= f.submit "Submit", :class => "btn waves-effect waves-light" %>
<% end %>

app/views/videos/edit.html.erb
<h1>Edit <%= @video.title %></h1>

<%= render 'videos/form' %>

app/views/videos/index.html.erb
<table class="striped bordered" style="margin: 50px">
 

  <% @videos.each do |video| %>
      <tr>
        <th  colspan="3" style="max-width: 80rem; margin: auto; text-align:center; font-size:50px; text-align: left; margin: auto"  >
<%= link_to video.title, video_path(video) %></th>
        </tr>
       <tr>
        <td style="padding: 10px;" ><%= image_tag(video.url, size: "300x300", alt: "Video Image")%></td>
        <td margin= "auto; margin: 10px"><%= video.des %></td>
        <td><a class="btn-floating btn-large red" href="<%= edit_video_path(video) %>" >
        <em class="large material-icons">Edit Video</em>
        <td><a class="btn-floating btn-large red"  data-method="delete" href="/videos/<%= video.id %>" rel="nofollow"><i class="large material-icons">Delete Video</i>

      </tr>
  <% end %>
<br>
</table>

app/views/videos/new.html.erb
<h1>New Video</h1>

<%= render 'videos/form' %>

app/views/videos/show.html.erb
  <h1><%= @video.title %> </h1>

  <%# <%= link_to "New video", new_video_path(:video_id => @video.id), { :class => "button waves-effect waves-light btn" } %>
  <%# <br><br> %> 
        <div><%= raw  (@video.video_url)%> </div> 
                <br>

        <div>
 <h5> Comments:</h5>
 </div>
  <div class="row">
    <% @video.comments.each do |comment| %>

         <div > <p><%= comment.content %></p> </div>
        </div>
        <br>
    <% end %>
      <br>
  </div>
    <%= link_to "New Comment", new_comment_path(:video_id => @video.id), { :class => "button waves-effect waves-light btn" } %>